version: '3.9'

services:
  postgres:
    image: postgres:14.3-alpine
    restart: always
    shm_size: 128mb

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - 5429:54322NT ["top", "-b"]